{{- $root := . }}

{{- with .Values.openethereum }}
{{- if .enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $root.Release.Name }}-openethereum
  labels:
    {{- include "eth2-validator.labels" $root | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  serviceName: {{ $root.Release.Name }}-openethereum
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $root.Release.Name }}-openethereum
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $root.Release.Name }}-openethereum
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "eth2-validator.openethereum.serviceAccountName" $root }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          args: [
            "--chain", {{ .network }},
            "--jsonrpc-interface=all",
            "--metrics",
            "--metrics-interface=all",
            "--base-path=/var/data/"
          ]
          ports:
            - name: jsonrpc
              containerPort: 8545
              protocol: TCP
            - name: metrics
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: /var/data
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  
  {{- if .persistent.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        {{- toYaml .persistent.accessModes | nindent 8 }}
      storageClassName: {{ .persistent.storageClassName }}
      resources:
        requests:
          storage: {{ .persistent.size }}
  {{- else }}
  volumes:
  - name: data
    emptyDir: {}
  {{- end }}

{{- end }}
{{- end }}
