{{- if .Values.openethereum.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openethereum
  labels:
    {{- include "eth2-validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openethereum.service.type }}
  ports:
    - port: 8545
      targetPort: jsonrpc
      protocol: TCP
      name: jsonrpc
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-openethereum
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
