{{- $root := . }}

{{- with .Values.beacon }}
{{- if .enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $root.Release.Name }}-test-node
  labels:
    {{- include "eth2-validator.labels" $root | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  serviceName: {{ $root.Release.Name }}-test-node
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $root.Release.Name }}-test-node
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/component: test-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $root.Release.Name }}-test-node
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        app.kubernetes.io/component: test-node
    spec:
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: test-node
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
          - |
            while true; do sleep 15 ; echo "background"; done
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end }}
{{- end }}
