{{- $root := . }}

{{- with .Values.validator }}
{{- if .enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $root.Release.Name }}-validator
  labels:
    {{- include "eth2-validator.labels" $root | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  serviceName: {{ $root.Release.Name }}-validator
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $root.Release.Name }}-validator
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $root.Release.Name }}-validator
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "eth2-validator.validator.serviceAccountName" $root }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      {{- if .secretName }}
      initContainers:
        - name: import-keystore
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
          - |
            set -e
            set -o pipefail
            cat "\n" | \
              lighthouse account validator import \
              --network {{ .network | quote }}
              --datadir /var/data \
              --directory /var/secret \
              --stdin-inputs
          volumeMounts:
          - name: data
            mountPath: /var/data
          - name: secret
            mountPath: /var/secret
            readOnly: true
      {{- end }}
      containers:
        - name: validator
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          args:
            {{- $args := concat .defaultArgs .extraArgs (list "--network" .network "--beacon-nodes" (.beaconNodes | default (printf "http://%s-beacon:5052" $root.Release.Name))) }}
            {{- if .secretName }}
            {{- $args = concat $args (list "--secrets-dir" "/var/secrets") }}
            {{- end }}
            {{- toYaml $args | nindent 12 }}
          ports:
            - name: http
              containerPort: 5052
              protocol: TCP
            - name: metrics
              containerPort: 5064
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            failureThreshold: 5
            periodSeconds: 10
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
          - name: data
            mountPath: /var/data
          {{- if .secretName }}
          - name: secret
            mountPath: /var/secret
            readOnly: true
          {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
    {{- if not .persistent.enabled }}
      - name: data
        emptyDir: {}
    {{- end }}
    {{- with .secretName }}
      - name: secret
        secret:
          secretName: {{ . | quote }}
    {{- end }}
    {{- if and .persistent.enabled (not .secretName) }}
        []
    {{- end }}
 
  {{- if .persistent.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        {{- toYaml .persistent.accessModes | nindent 8 }}
      storageClassName: {{ .persistent.storageClassName }}
      resources:
        requests:
          storage: {{ .persistent.size }}
  {{- end }}

{{- end }}
{{- end }}
